kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  mapping.yaml: |
    mappings:
    {{ .Values.mappings | toYaml | nindent 6 }}